language: node_js

sudo: false

# track upstream node_js matrix:
# - https://github.com/hexojs/hexo/blob/master/.travis.yml
# - https://github.com/sass/node-sass/blob/master/.travis.yml
node_js:
  - "4"
  - "6"
  - "7"

script:
  - npm run build